Actividad Arrays Unidimensionales de Victor Carranza

In [1]:
import numpy as np

In [2]:
#1.- Crea un vector con valores dentro del rango 3 a el número que  representa tu edad.
vector = np.array(range(3,25))
vector

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24])

In [3]:
#2.- Crea un arreglo con los siguientes elementos:
arreglo = np.array([0,1,2,3,4,0,1,2,3,4])
arreglo

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [4]:
#3.- Ordena de forma ascendiente dicho arreglo.
arreglo.sort()
arreglo

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])